# This is a basic workflow

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up Node
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Run install dependencies
      - name: Install dependencies
        run: yarn

      # Package vsix
      - name: Build .vsix package on Linux
        run: |
          VERSION=$(node -p "require('./package.json').version")
          npx vsce package -o vscode-backstage-${VERSION}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}.vsix

      # Upload vsix
      - name: Upload linux-built vsix
        uses: actions/upload-artifact@v2
        with:
          name: vscode-backstage
          path: vscode-backstage*.vsix
